_IGNORE := '\s+|/\*.*?\*/|//.*?\n'
Code := '@\{[.\n]*?\}@'
FloatNumber := '-?[1-9][0-9]*\.[0-9]*' : [0]
IntNumber := '-?[1-9][0-9]*' : [1]
String := '".*?[^\\]"|""'
Id := '[a-zA-Z_][a-zA-Z_0-9]*'

%%%

$ := <Statement>

<Statement> := <PropertyStatement> : [1]
    := <Statement> ';' : [2]
    := : [3]

<BaseValueNumber> := IntNumber | FloatNumber : [4]
    := Id '(' [  <BaseValueNumber> {',' <BaseValueNumber> } ] ')' : [5]


<VariableDefine> := Id [ '<' Id '>' ] Id [ '[' IntNumber ']' ] [ '=' ( String | 'true' | 'false' | <BaseValueNumber> ) ] : [6]

<StructDesc> := 'struct' Id '{' { <VariableDefine> | ';' } '}' ';' : [7]

<MateDateElement> := Id [ '=' ( <BaseValueNumber> | String | 'true' | 'false' ) ]

<MateDate> := [ '[' [<MateDateElement> {',' <MateDateElement> } ] ']' ]

<PropertyDefine> := <PropertyDefine> <MateDate> '{' <PropertyDefine> '}'
    := <PropertyDefine> <MateDate> <VariableDefine> ';'
    := <PropertyDefine> ';'
    :=

<PropertyStatement> := 'property' '{' <PropertyDefine> '}'

/*

<DefineProperty> := <MateDate> <Type> Id { '[' IntNumber ']' } [ '=' <ConstNumber>  ]

<DefinePropertyStatement> := <DefinePropertyStatement> <DefineProperty> ';'
    := <DefinePropertyStatement> <MateDate> '{' <DefinePropertyStatement> '}'
    := 
    := <DefinePropertyStatement> ';'

<ImportStatement> := 'import' String 'as' Id ';'

<PropertyStatement> := 'property' '{' <DefinePropertyStatement>  '}' ';'

<IncludeElement> := Id
    := <IncludeElement> '.' Id

<IncludeElementList> := <IncludeElement>
    := <IncludeElementList> ',' <IncludeElement>

<Include> := '[' <IncludeElementList> ']'
    := '[' ']'
    :=

<CodeStatement> := 'code' Id <Include> Code ';'

<Conflig> := '<' <MateDateElementList> '>'
    := '<' '>'

<InoutElementList> := <NumberType> Id
    := <InoutElementList> ',' <NumberType> Id

<Inout> := '(' <InoutElementList> ')'
    := '(' ')'

<SectionStatement> := 'section' Id <Include> <Inout> '->' <Inout> Code ';'
<DefineMarcoStatement> := 'define' Id String ';'
    := 'define' Id ';'

<MaterialStatementElement> := <MaterialStatementElement> <SectionStatement>
    := <MaterialStatementElement> <DefineMarcoStatement>
    := 

<MaterialStatement> := <NullableMateData> 'material' Id 'as' Id <Conflig> '{' <MaterialStatementElement> '}' ';'
    := <NullableMateData> 'using' 'material' <IncludeElement> 'as' Id <Conflig> ';'



<StatemenetElement> :=  <StatemenetElement> <ImportStatement>
    := <StatemenetElement> <CodeStatement>
    := <StatemenetElement> <MaterialStatement> 
    := 

<Statement> := <StatemenetElement>
    := <PropertyStatement> <StatemenetElement>

*/


