_IGNORE := '\s+|/\*.*?\*/|//.*?\n'
Code := '@\{[.\n]*?\}@'
FloatNumber := '-?[1-9][0-9]*\.[0-9]*' : [0]
IntNumber := '-?[1-9][0-9]*' : [1]
String := '".*?[^\\]"|""'
Id := '[a-zA-Z_][a-zA-Z_0-9]*'

%%%

$ := <Statement>

<Statement> := <PropertyStatement> : [1]
    := <Statement> ';' : [2]
    := : [3]

<BaseConstValue> := IntNumber | FloatNumber : [4]
    := 'true' : [5]
    := 'false': [6]
    := String : [7]

<BaseValueNumber> := <BaseConstValue> : [8]
    := Id '(' [ <BaseConstValue> {',' <BaseConstValue> } ] ')' : [9]
    := String : [10]

<DefineVariable> := Id [ '<' Id '>' ] Id : [11]
    := Id [ '<' Id '>' ] Id '[' IntNumber ']' : [12]

<DefineOrInitVariable> := <DefineVariable> [ '=' <BaseValueNumber> ] : [13]

<StructDesc> := 'struct' Id '{' { <DefineVariable> ';' | ';' } '}' ';' : [14]

<MateDateElement> := Id [ '=' <BaseValueNumber> ] : [15]

<MateDate> := [ '[' [<MateDateElement> {',' <MateDateElement> } ] ']' ] : [16]

<PropertyDefine> := <PropertyDefine> <MateDate> '{' <PropertyDefine> '}' : [17]
    := <PropertyDefine> <MateDate> <VariableDefine> ';' : [18]
    := <PropertyDefine> ';' : [19]
    := : [20]

<PropertyStatement> := 'property' '{' <PropertyDefine> '}' : [21]

/*

<DefineProperty> := <MateDate> <Type> Id { '[' IntNumber ']' } [ '=' <ConstNumber>  ]

<DefinePropertyStatement> := <DefinePropertyStatement> <DefineProperty> ';'
    := <DefinePropertyStatement> <MateDate> '{' <DefinePropertyStatement> '}'
    := 
    := <DefinePropertyStatement> ';'

<ImportStatement> := 'import' String 'as' Id ';'

<PropertyStatement> := 'property' '{' <DefinePropertyStatement>  '}' ';'

<IncludeElement> := Id
    := <IncludeElement> '.' Id

<IncludeElementList> := <IncludeElement>
    := <IncludeElementList> ',' <IncludeElement>

<Include> := '[' <IncludeElementList> ']'
    := '[' ']'
    :=

<CodeStatement> := 'code' Id <Include> Code ';'

<Conflig> := '<' <MateDateElementList> '>'
    := '<' '>'

<InOutFlag> := 'in'
    := 'out'
    :=

<InoutElementList> := <InOutFlag> 'in' <NumberType> Id
    := <InoutElementList> ',' <InOutFlag> <NumberType> Id

<SectionStatement> := 'section' Id <Include> '(' [<InoutElementList>] ')' Code ';'

<DefineMarcoStatement> := 'define' Id String ';'
    := 'define' Id ';'

<MaterialStatementElement> := <MaterialStatementElement> <SectionStatement>
    := <MaterialStatementElement> <DefineMarcoStatement>
    := 

<MaterialStatement> := <NullableMateData> 'material' Id 'as' Id <Conflig> '{' <MaterialStatementElement> '}' ';'
    := <NullableMateData> 'using' 'material' <IncludeElement> 'as' Id <Conflig> ';'



<StatemenetElement> :=  <StatemenetElement> <ImportStatement>
    := <StatemenetElement> <CodeStatement>
    := <StatemenetElement> <MaterialStatement> 
    := 

<Statement> := <StatemenetElement>
    := <PropertyStatement> <StatemenetElement>

*/


